### ISSUE TITLE
it is not available to set item which i want to set  in center

### ISSUE THREAD

**Issue by i2863CookieZJ** [TakuSemba/MultiSnapRecyclerView#11]
i set  app:msrv_gravity="center",how can i set any item to "center" or  use the code to let it scroll to next item?can u help me

**Comment by TakuSemba** [comment]
>  i set any item to "center

you can't set **any** item to the specified gravity, for example, if `msrv_snap_count = 3` every 3 items can be scrolled to the specified gravity.

>  use the code to let it scroll to next item

I think this could be archivable using functionalities of RecyclerView, but I haven't tried yet.
I'll let you know if I tested it.

**Comment by i2863CookieZJ** [comment]
thank u for your answer,expect it coming soon

**Comment by mibrahimdev** [comment]
any update in this?
