### ISSUE TITLE
A warning appear.

### ISSUE THREAD

**Issue by Ahyounglove** [TakuSemba/MultiSnapRecyclerView#14]
A warning appears when i swipe from the recyclerview.
The test machine is the Nexus 5x  android 7.0 version api 24.
Can I ignore it? 

 E/RecyclerView: Smooth Scroll action is being updated too frequently. Make sure you are not changing it unless necessary

**Comment by TakuSemba** [comment]
Hi, sorry for the late response.
I recently released version 2.0.0 with lots of fixes.

Can you try it out and see if it still happens?

**Comment by TakuSemba** [comment]
Please reopen this if this still happens on v2.x.x. Thank you.
