### ISSUE TITLE
Any idea how to handle screen orientation?

### ISSUE THREAD

**Issue by sosasang** [TakuSemba/MultiSnapRecyclerView#21]
Gravity: Center
Snap Count: 1
Orientation: Vertical
Portrait: showing multiple items depends on the item height
Landscape: showing one item in fullscreen
I did recycler_view.scrollToPosition() in onConfigurationChanged.
Portrait -> Landscape is working fine
Landscape -> Portrait: the item is in top, instead of center, until you scroll again

**Comment by TakuSemba** [comment]
I think you can archive that by restoring the scroll position at View#onSaveInstanceState / View#onRestoreInstanceState then scroll to the restored position.

Also, this is not this library's responsibility.
I'm closing this issue.
