### ISSUE TITLE
Not able to show last item with gravity start

### ISSUE THREAD

**Issue by azri92** [TakuSemba/MultiSnapRecyclerView#23]
I found a bug where the list is preventing the last item to be shown when `app:msrv_gravity="start"` is set.

Screen recording of issue with library's sample app:
[end not snapping with gravity start normal font.mp4.zip](https://github.com/TakuSemba/MultiSnapRecyclerView/files/4184860/end.not.snapping.with.gravity.start.normal.font.mp4.zip)

Phone: OnePlus One
Android Version: 6.0.1

**Edit**
Apparently this happens to first item when `app:msrv_gravity="start"` is set with `app:msrv_interval="2"`

**Comment by TakuSemba** [comment]
I fixed it at the version of 2.0.2. 👍
