### ISSUE TITLE
Hi, thank you for the request.

### ISSUE THREAD

**Issue by buornhnufnofnr** [TakuSemba/MultiSnapRecyclerView#25]
Hi, thank you for the request.

I'm just wondering if `recyclerView.smoothScrollToPosition(position)` does not work for your case?
It would be helpful if you could give me a situation you want to scroll with `SnapHelpe

**Comment by TakuSemba** [comment]
I'm closing this because it does not make sense and seems like the sentences were copy&pasted from somewhere else.
