### ISSUE TITLE
How to get the middle value

### ISSUE THREAD

**Issue by anvesh523** [TakuSemba/MultiSnapRecyclerView#3]
Hey, Your did a good work. I want to know, how to get the middle value of the adapter programmatically.

**Comment by TakuSemba** [comment]
Ok, Ill try to return position inside OnSnapListener in the next version

**Comment by TakuSemba** [comment]
1.1.0 has just released
now you can access the position with OnSnapListener(int position)

**Comment by anvesh523** [comment]
Excellent work, thank you.
