### ISSUE TITLE
RecyclerView scrolling is too slow.

### ISSUE THREAD

**Issue by parveenkumardeeva** [TakuSemba/MultiSnapRecyclerView#4]
Hi TakuSemba,

After attaching your code the recycler scroll works too slow.
Either it's just scroll to msrv_snap_count or if we define higher value then it skips all the items.

**Comment by anvesh523** [comment]
I feel the same.

**Comment by sumonhub** [comment]
am also

**Comment by Aetherna** [comment]
Yep the fling is not working, made me ditch this library although it's very cool :(

**Comment by TakuSemba** [comment]
ok, i'll try to fix it.

**Comment by TakuSemba** [comment]
@parveenkumardeeva @anvesh523 @SumonHub @Aetherna 
now you can control the speed of scrolling through as of version 1.2.0

**Comment by XiongKe94** [comment]
am also
