### ISSUE TITLE
Version 1.1.0 released, but code here shows it's 1.0.3

### ISSUE THREAD

**Issue by AndrewWestberg** [TakuSemba/MultiSnapRecyclerView#6]
This repository seems to not be up to date with what has been released.

**Comment by TakuSemba** [comment]
you mean gradle file doesn't sync with 1.1.0???...
It's not happening to me...
can i see your build.gradle ???

**Comment by AndrewWestberg** [comment]
The build.gradle in this repository on the master branch still shows 1.0.3, not 1.1.0.

**Comment by TakuSemba** [comment]
thanks, I fixed it.
