### ISSUE TITLE
java.lang.IllegalArgumentException: other than LinearLayoutManger is not supported

### ISSUE THREAD

**Issue by geoffery009** [TakuSemba/MultiSnapRecyclerView#9]
use MultiSnapRecyclerView in a RecyclerView item

                    MultiSnapRecyclerView snapRecyclerView = null;
                    SkipAppAdapter appAdapter = new SkipAppAdapter(snapRecyclerView, data.getFastInDataBean());
                    snapRecyclerView = holder.getView(R.id.snapRecycleView);
                    LinearLayoutManager layoutManager = new LinearLayoutManager(getContext(), LinearLayoutManager.HORIZONTAL, false);
                    snapRecyclerView.setLayoutManager(layoutManager);
                    snapRecyclerView.setAdapter(appAdapter);

                    snapRecyclerView.setOnSnapListener(new OnSnapListener() {
                        @Override
                        public void snapped() {
                            // do something
                        }
                    });

**Comment by TakuSemba** [comment]
i solved it at #8 
reopen if it still happens
